"""Add reason

Revision ID: 5feec4046926
Revises: 6458bd3b46dc
Create Date: 2018-01-30 20:14:32.375492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5feec4046926'
down_revision = '6458bd3b46dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iou', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iou', 'reason')
    # ### end Alembic commands ###
