"""Add pending flag

Revision ID: 6458bd3b46dc
Revises: da4dcbacbe0e
Create Date: 2017-11-26 07:32:09.814699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6458bd3b46dc'
down_revision = 'da4dcbacbe0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iou', sa.Column('pending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iou', 'pending')
    # ### end Alembic commands ###
